export const GET_VIDEO_REQUEST= "GET_VIDEO_REQUEST";
export const GET_VIDEO_SUCCESS= "GET_VIDEO_SUCCESS";
export const GET_VIDEO_FAILURE= "GET_VIDEO_FAILURE";
export const GET_SEARCH_VIDEO="GET_SEARCH_VIDEO";
export const GET_UPDATE_VIDEO="GET_UPDATE_VIDEO"
